### PR TITLE
Fix the bug where negative voltages were measured incorrectly.

### PR DESCRIPTION
**Pull request by thegoodhen**

### CODE REVIEW

**Review by mjklopfer — COMMENTED** [review]
I haven't tested on our demo board for the MCP3903, but this makes sense with how the casting approach and we had to a similar approach with other ADCs in the past.  Have you confirmed this as working on your hardware @thegoodhen ?  I hope @kerrydwong is continuing to maintain this helpful project.

**Comment by thegoodhen** [comment]
> I haven't tested on our demo board for the MCP3903, but this makes sense with how the casting approach and we had to a similar approach with other ADCs in the past. Have you confirmed this as working on your hardware @thegoodhen ? I hope @kerrydwong is continuing to maintain this helpful project.

Before the fix, I was getting erroneous readings around 420 volts for negative voltages; after the fix, the voltages are more or less correct. Since my hardware isn't yet calibrated, there is the distant possibility that the negative readings are still off by a bit or something similar, but I have done initial tests and it is looking good.

**Comment by mjklopfer** [comment]
@thegoodhen - just trying to reproduce on our side, just curious are you using a crystal driven by the MCP3903 or an external supplied clock off board?  Are you driving with 4.0 MHz?  Trying to debug another issue jumping back in on our hardware.

**Comment by thegoodhen** [comment]
> @thegoodhen - just trying to reproduce on our side, just curious are you using a crystal driven by the MCP3903 or an external supplied clock off board? Are you driving with 4.0 MHz? Trying to debug another issue jumping back in on our hardware.

I'm using a 4Mhz crystal oscillator with 33p capacitors. Have been getting some weird asymmetry though, as it seems like the positive voltages and negative voltages of the same magnitude seem to lead to slightly different results.  But there might just be a problem with my circuit, as it's still on breadboard.

Have you guys used a 4 layer board? Right now I am using a breadboard and I know I cant expect to get 24 bits resolution out of it, but I am averaging 1000 samples on 256 OSR and I barely can get down in the millivolt range... seems a bit dodgy, not sure where the problem is...

**Comment by thegoodhen** [comment]
> > @thegoodhen - just trying to reproduce on our side, just curious are you using a crystal driven by the MCP3903 or an external supplied clock off board? Are you driving with 4.0 MHz? Trying to debug another issue jumping back in on our hardware.
> 
> I'm using a 4Mhz crystal oscillator with 33p capacitors. Have been getting some weird asymmetry though, as it seems like the positive voltages and negative voltages of the same magnitude seem to lead to slightly different results. But there might just be a problem with my circuit, as it's still on breadboard.
> 
> Have you guys used a 4 layer board? Right now I am using a breadboard and I know I cant expect to get 24 bits resolution out of it, but I am averaging 1000 samples on 256 OSR and I barely can get down in the millivolt range... seems a bit dodgy, not sure where the problem is...

Hm, ok, fixed that... turns out I was just overestimating the precision of floats when trying to average the samples by summing them and then dividing by their count. :D

**Pull request merged**
